### ISSUE TITLE
Movim timeouts/refresh after 60 seconds of inactivity

### ISSUE THREAD

**Issue by alexAubin** [src386/movim_ynh#10]
Dear src386, thank you very much for your packaging - the install was very smooth on my side :).

One complain though, after logging in, Movim refreshes after 60 seconds of inactivity and goes back to login screen, which is a bit annoying since you constantly have to log back in. This seem to be caused by [this commit](https://github.com/src386/movim_ynh/commit/d9824c02d5c35c4cea95b638d264e48a71c2cfef), as adding the timeout lines back fixed the issue. Is there any motivation to keep this timeout low instead of something >= 3600 for instance ?

Cheers,

Alex

**Comment by src386** [comment]
Hi alexAubin,
Thank you. I removed the timeout option because it was set to 1 day (seems excessive) with no explanation.
I will try your suggestion and update the package if it works.

**Comment by src386** [comment]
Should be fixed (in master), thanks.
