### ISSUE TITLE
Minor problems when running update script

### ISSUE THREAD

**Issue by alexAubin** [src386/movim_ynh#11]
When running the update scripts in command line to move to 0.9 git2015-11-13  :
```sudo yunohost app upgrade -u https://github.com/src386/movim_ynh movim```

During the following step : 
```+ sudo su -c 'cd /var/www/movim && php composer.phar update' movim```
I was asked for some changes wether to discard them or abort the update, and so on. I chose "y - discard changes and apply the update" which seems to have done the trick. Ideally this could be automatized =D.

Also after the update completed, the movim daemon stopped. According to the log, the database needed to be updated with `php mud.php db set`. Running the command in the movim folder + restarting the daemon solved the issue.

**Comment by src386** [comment]
Hi again,
yes, sorry for this. I am aware of this issue, it's fixed in the dev branch.
I think I will push a minor release to fix it.
Thanks for the ticket
Xavier.

**Comment by src386** [comment]
Fixed in master :)
