### ISSUE TITLE
Consider asking the user timezone

### ISSUE THREAD

**Issue by mbugeia** [src386/movim_ynh#15]
Hi,
I'm not sure that reading /etc/timezone is the best for user experience. 

For example I run yunohost on a VPS in London which has America/New_York as /etc/timezone but I live in France. I don't care about my server timezone but I care about the time in see when chatting.

So maybe the timezone should be asked to the user at install. What do you think ? In an ideal world Movim should read the timezone directly on the client computer via javascript like Jappix.

**Comment by src386** [comment]
Hello,

It would be best to just set your server to Europe/Paris, this is what I did with mine (located in Netherlands). If it's not possible, you can change that parameter in movim : https://yourpod.org/movim/?admin then go to the "General Settings" tab.

I'm not sure it's a good idea to add this option in the package installation, it's advanced usage...

You can suggest this feature to Movim, it's not a bad idea : https://github.com/edhelas/movim :)

**Comment by mbugeia** [comment]
Well I don't consider this being advanced but I didn't know that we can change it. Is there a button for the admin page somewhere or you just have to know about it ?
I understand that you do not want to do this in the package (and it's not trivial to do anyway) and will open an issue on movim repository.

**Comment by src386** [comment]
I don't think there is any button. it's a Movim feature so there is probably some documentation.

In fact my idea is to keep the package simple and use /?admin for advanced settings.

**Comment by src386** [comment]
Do you mind if I close the issue ?

**Comment by mbugeia** [comment]
I don't ;)

**Comment by src386** [comment]
Thanks !
