### ISSUE TITLE
Blank page after installation

### ISSUE THREAD

**Issue by src386** [src386/movim_ynh#6]
Sometimes after Movim installation you get a blank page.
This in a issue with permissions.
Temporary workarround : 

    # chown -R movim:www-data /var/www/movim
    # chmod -R 770 /var/www/movim

**Comment by src386** [comment]
This also happens when a MySQL random password contains special characters.

**Comment by Kloadut** [comment]
I run into this issue just after the installation, even with your permission workaround:

```
PHP message: PHP Fatal error:  require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/movim/bootstrap.php on line 4" while reading response header from upstream, client: 10.0.242.146, server: brique.kload.fr, request: "GET /movim/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "brique.kload.fr", referrer: "https://brique.kload.fr/yunohost/sso/"
```

**Comment by src386** [comment]
Yeah it's totally broken.
It's fixed in dev but there is another bug, which is related to upstream movim.
I'm waiting for a fix to that bug. After that I can push to master.

**Comment by src386** [comment]
Should be fixed now.
However you will be disconnected soon after connecting.
This is the movim bug, still waiting for upstream fix.

**Comment by Kloadut** [comment]
Awesome, thanks :)
